In [1]:
# coding: utf-8
import numpy as np


class Sigmoid:
    def __init__(self):
        self.params = []

    def forward(self, x):
        return 1 / (1 + np.exp(-x))


class Affine:
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out


class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 重みとバイアスの初期化
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # レイヤの生成
        self.layers = [Affine(W1, b1), Sigmoid(), Affine(W2, b2)]

        # すべての重みをリストにまとめる
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x


x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print(s)

[[ 2.14712955 -1.47928507  0.3327347 ]
 [ 3.18001062 -2.26394751  1.69270486]
 [ 2.88681818 -2.00835557  1.2220095 ]
 [ 2.22955265 -1.51952007  0.3831079 ]
 [ 3.44709457 -2.41608242  1.90845262]
 [ 2.14005538 -1.34290284 -0.06566851]
 [ 2.80162741 -1.87213315  0.89139663]
 [ 2.34362903 -1.61514289  0.57603209]
 [ 2.85000079 -1.95084997  1.08373344]
 [ 1.98668642 -1.29256717 -0.09982143]]
